### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported anymore

### ISSUE THREAD

**Issue by matissg** [605data/strongbolt_example#3]
I'm trying to set your example app and when I add in **config\initializers\strongbolt.rb**
`config.skip_controller_authorization_for "Devise::Sessions", "Devise::Registrations"`

I get this error in my terminal:
```
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/home/ubuntu/.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:710:in `block (2 levels) in skip_callback': Before process_action callback :check_authorization has not been defined (ArgumentError)
#more lines follow...
```
When I comment that config line, I can see your demo app's login page and when I log in, I get error that there is no Model corresponding Devise::SessionsController#create. As I understand Strongbolt is working as expected - there has to be a model otherwise it will rise error.

**How do white-list those Devise controllers, please?** So far I've set Devise as it is said in [Getting Started](https://github.com/plataformatec/devise#getting-started).

**Comment by tobithiel** [comment]
You're trying to follow the steps to set an app up from scratch?

To me it looks like Strongbolt isn't fully loaded yet, since `check_authorization` is not defined which Strongbolt defines on all controllers when loaded. Did you run `rails g strongbolt:install`? Can you provide the full stack trace and the steps you performed to get to this point?

**Comment by matissg** [comment]
I'm trying to set up your example app. Initially I did everything as it was in description, but then I got several errors, e.g.:
```
ubuntu@ubuntu-xenial:/vagrant/strongbolt$ rails g strongbolt:install && rake db:migrate
Running via Spring preloader in process 2925
      create  db/migrate/20170522165515_create_strongbolt_tables.rb
      create  config/initializers/strongbolt.rb
        gsub  config/initializers/strongbolt.rb
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateStrongboltTables < ActiveRecord::Migration[4.2]
```
Then I just copied your example app, then did all DB setup, installed Devise, Simple Form and Strongbolt. I have all tables as in your description.
Now I tried to do everything from scratch and on fresh Rails 5.1.1. instalation this is what I get:
```
ubuntu@ubuntu-xenial:/vagrant/strongbolt$ rails g strongbolt:install
Running via Spring preloader in process 2841
      create  db/migrate/20170522191736_create_strongbolt_tables.rb
      create  config/initializers/strongbolt.rb
        gsub  config/initializers/strongbolt.rb
ubuntu@ubuntu-xenial:/vagrant/strongbolt$ rails db:migrate
rails aborted!
ActiveRecord::StatementInvalid: Could not find table 'strongbolt_capabilities'
/home/ubuntu/.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:417:in `table_structure'
#more lines follow...
```
It seems to be something wrong with the migration, right? Strongbolt migration is in db/migrate however I cannot do `rails db:migrate`

**Comment by tobithiel** [comment]
The migrations failed so the relevant tables don't exist. Can you try using a Rails version before 5.1.1? They deprecated `MyMigration < ActiveRecord::Migration` and require `MyMigration < ActiveRecord::Migration[version]` now.
We'll push out an update to stay compatible soon.

**Comment by tobithiel** [comment]
I'm gonna close this in favor of 605data/strongbolt#31. Some gems from this example depend on Rails 5.1. So we can't upgrade to the newest Rails here yet.
